GET http://localhost:5000/users  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJuYW1lIjoiYWRpIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE2OTAzNDI3NjgsImV4cCI6MTY5MDM0Mjc4OH0.Ie9sAjlX3HJ9lgaN61gZt3KCQUI6cjk9cxcWvD2VElw
###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "adi",
    "email": "email@gmail.com",
    "password": "19809",
    "confPassword":"19809"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "19809"
}

###
GET http://localhost:5000/token
###
POST  http://localhost:5000/users

###
DELETE  http://localhost:5000/logout